### ISSUE TITLE
Rust package built as x86_64 on arm64 macOS

### ISSUE THREAD

**Issue by messense** [catboost/catboost#2180]
Problem: Rust package built as x86_64 on arm64 macOS while it should build for arm64
catboost version: master 32828dd5f3d6e168a22f61ccede86c066c53d474
Operating System: macOS
CPU: Apple M2

**Cargo.toml**

```toml
[package]
name = "catboost-dep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
catboost = { git = "https://github.com/catboost/catboost" }
```

**src/main.rs**

```rust
use catboost;

pub fn main() {
    // Load the trained model
    let model = catboost::Model::load("tmp/model.bin").unwrap();

    println!("Number of cat features {}", model.get_cat_features_count());
    println!(
        "Number of float features {}",
        model.get_float_features_count()
    );

    // Apply the model
    let prediction = model
        .calc_model_prediction(
            vec![
                vec![-10.0, 5.0, 753.0],
                vec![30.0, 1.0, 760.0],
                vec![40.0, 0.1, 705.0],
            ],
            vec![
                vec![String::from("north")],
                vec![String::from("south")],
                vec![String::from("south")],
            ],
        )
        .unwrap();
    println!("Prediction {:?}", prediction);
}
```

Verbose build log shows

```
[catboost-sys 0.1.0] Current target architecture is x86_64. Specify "--target-platform" flag to build for native arm64.
[catboost-sys 0.1.0] Warn: Can't use YT cache: No module named yt_store... <Truncated. Complete message will be available in debug logs>
[catboost-sys 0.1.0] Ok
```

Rust version

```bash
$ rustc -vV
rustc 1.64.0 (a55dd71d5 2022-09-19)
binary: rustc
commit-hash: a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52
commit-date: 2022-09-19
host: aarch64-apple-darwin
release: 1.64.0
LLVM version: 14.0.6
```
